//
//  DetailBookPresenter.swift
//  BookApp
//
//  Created by Julia on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBookPresentationLogic
{
  func presentSomething(response: DetailBook.GetBook.Response)
}

final class DetailBookPresenter: DetailBookPresentationLogic
{
  weak var viewController: DetailBookDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DetailBook.GetBook.Response)
  {
      let bookInfo = response.bookInfo
      let authors = bookInfo.authors.joined(separator: ", ")
      let categories = bookInfo.categories?.joined(separator: " | ")
      let thumbnailURL = URL(string: bookInfo.imageLinks!.thumbnail)!
      let displayedBook = DetailBook.GetBook.ViewModel.DisplayedBook(title: bookInfo.title,
                                                                     author: authors,
                                                                     thumbnailURL: thumbnailURL,
                                                                     pageCount: "\(bookInfo.pageCount) 쪽",
                                                                     categories: categories,
                                                                     description: bookInfo.description,
                                                                     publisher: bookInfo.publisher,
                                                                     publishedDate: bookInfo.publishedDate)
      
    let viewModel = DetailBook.GetBook.ViewModel(displayedBook: displayedBook)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
