//
//  DetailBookInteractor.swift
//  BookApp
//
//  Created by Julia on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBookBusinessLogic
{
  func doSomething(request: DetailBook.Something.Request)
}

protocol DetailBookDataStore
{
  var book: Book? { get set }
}

class DetailBookInteractor: DetailBookBusinessLogic, DetailBookDataStore
{
    var book: Book?
    
  var presenter: DetailBookPresentationLogic?
  var worker: DetailBookWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: DetailBook.Something.Request)
  {
    worker = DetailBookWorker()
    worker?.doSomeWork()
    
    let response = DetailBook.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
