//
//  DetailBookInteractor.swift
//  BookApp
//
//  Created by Julia on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBookBusinessLogic {
    func fetchBook(request: DetailBook.FetchBook.Request)
}

protocol DetailBookDataStore {
    var book: Book? { get set }
}

final class DetailBookInteractor: DetailBookBusinessLogic, DetailBookDataStore {
    
    enum FetchBookError: String {
        case noBookResponse = "선택한 책 정보가 없습니다."
    }
    
    var book: Book?
    var presenter: DetailBookPresentationLogic?
    
    func fetchBook(request: DetailBook.FetchBook.Request) {
//        book = nil // TODO: 에러 테스트 위함
        if let book = book {
            let response = DetailBook.FetchBook.Response(book: book)
            presenter?.presentFetchBook(response: response)
        } else {
            presenter?.presentFetchBookError(response: .init(message: FetchBookError.noBookResponse.rawValue))
        }
    }
}
