//
//  DetailBookRouter.swift
//  BookApp
//
//  Created by Julia on 2023/03/09.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailBookRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DetailBookDataPassing
{
  var dataStore: DetailBookDataStore? { get }
}

final class DetailBookRouter: NSObject, DetailBookRoutingLogic, DetailBookDataPassing
{
  weak var viewController: DetailBookViewController?
  var dataStore: DetailBookDataStore?
  
}
