//
//  SearchBookRouter.swift
//  BookApp
//
//  Created by Julia on 2023/03/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchBookRoutingLogic
{
    func routeToDetailBooks(_ selectedIndex: Int)
}

protocol SearchBookDataPassing
{
  var dataStore: SearchBookDataStore? { get }
}

final class SearchBookRouter: NSObject, SearchBookRoutingLogic, SearchBookDataPassing
{
  
  weak var viewController: SearchBookViewController?
  var dataStore: SearchBookDataStore?
  
    // MARK: - Routing
    func routeToDetailBooks(_ selectedIndex: Int) {
        if let detailVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "DetailBookViewController") as?  DetailBookViewController,
           var detailDS = detailVC.router?.dataStore {
            passDataToDetailBook(source: dataStore!, destination: &detailDS, index: selectedIndex)
            navigateToDetailBook(source: viewController!, destination: detailVC)
        }
    }
    
    // MARK: - Navigation
    func navigateToDetailBook(source: SearchBookViewController, destination: DetailBookViewController)
  {
      source.navigationController?.pushViewController(destination, animated: true)
  }
  
    // MARK: -  Passing data
    func passDataToDetailBook(source: SearchBookDataStore, destination: inout DetailBookDataStore, index: Int)
  {
      if let selectedBook: Book = source.books?.items[index] {
          destination.book = selectedBook.volumeInfo
      }
  }
}
