//
//  SearchBookPresenter.swift
//  BookApp
//
//  Created by Julia on 2023/03/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBookPresentationLogic
{
  func presentSomething(response: SearchBook.FetchBooks.Response)
}

class SearchBookPresenter: SearchBookPresentationLogic
{
  weak var viewController: SearchBookDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SearchBook.FetchBooks.Response)
  {
      let viewModel = SearchBook.FetchBooks.ViewModel(displayedBooks: [])
    viewController?.displaySomething(viewModel: viewModel)
  }
}
