//
//  SearchBookInteractor.swift
//  BookApp
//
//  Created by Julia on 2023/03/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBookBusinessLogic
{
    func fetchBooks(request: SearchBook.FetchBooks.Request)
}

protocol SearchBookDataStore
{
    var books: Books? { get }
}

final class SearchBookInteractor: SearchBookBusinessLogic, SearchBookDataStore
{
    var presenter: SearchBookPresentationLogic?
    
    var books: Books?
    private var bookWorker = SearchBookWorker(booksStore: BooksStaticStore()) // TODO: API 연동하면 바꾸기
    
    func fetchBooks(request: SearchBook.FetchBooks.Request) {
        
        Task {
            do {
                let books = try await self.bookWorker.fetchBooks()
                self.books = books
                let response = SearchBook.FetchBooks.Response(books: books)
                self.presenter?.presentFetchedBooks(response: response)
            } catch {
                
            }
        }
        
    }
}
